default_stages:
  - commit
  - push
repos:
  -   repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          args: ["--profile", "black"]
  -   repo: https://github.com/hadialqattan/pycln
      rev: v2.4.0
      hooks:
        - id: pycln
          args: [--all]
  -   repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
        - id: black
  -   repo: https://github.com/DanielNoord/pydocstringformatter
      rev: v0.7.3
      hooks:
        - id: pydocstringformatter
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
          args: [ --allow-multiple-documents ]
        - id: check-added-large-files
          args: [ --maxkb=5000 ]
  -   repo: https://github.com/pycqa/flake8
      rev: '7.0.0'
      hooks:
        - id: flake8
  -   repo: https://github.com/Yelp/detect-secrets
      rev: v1.4.0
      hooks:
        - id: detect-secrets
          files: ".*"
