@startuml
skinparam componentStyle uml2
actor Клиент as Client
component WebApp
component LegacyWebBackend
database PostgresReplica
database LegacyElastic

Client -> WebApp: Просмотр истории бонусов
WebApp -> LegacyWebBackend: Просмотр истории бонусов
LegacyWebBackend -> PostgresReplica
LegacyWebBackend -down-> LegacyElastic
@enduml