version: '3'

services:

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.7.1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"

volumes:
    elasticsearch_data: