#!/usr/bin/env python3
import sys
import time
import uuid


def main():
    # Считывание всего входного потока, который будет содержать заголовки и тело сообщения
    email_content = sys.stdin.read()
    # Формирование уникального имени файла с текущей временной меткой
    timestamp = time.strftime("%Y%m%d-%H%M%S")

    # id
    id = uuid.uuid4()

    # Запись содержимого в файл с расширением .eml
    with open(f"/app/mailings/fake_mail_{timestamp}-{id}.eml", 'w') as file:
        file.write(email_content)


if __name__ == "__main__":
    main()
