"""yandex-oauth-table

Revision ID: 7f5b408e322e
Revises: e52593e48832
Create Date: 2024-03-08 01:18:12.691071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5b408e322e'
down_revision: Union[str, None] = 'e52593e48832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yandex_oauth',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('default_email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_in', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.uuid'],ondelete='CASCADE' ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('default_email'),
    sa.UniqueConstraint('uuid'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yandex_oauth', schema='users')
    # ### end Alembic commands ###
