"""empty message

Revision ID: 9d4fc6612143
Revises: 61b961cce125
Create Date: 2024-02-25 15:29:53.588916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9d4fc6612143'
down_revision: Union[str, None] = '61b961cce125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('uuid', sa.UUID(), nullable=False),
                    sa.Column('role', sa.String(length=255), nullable=False),
                    sa.Column('resource', sa.String(length=255), nullable=False),
                    sa.Column('verb', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('uuid'),
                    schema='users'
                    )
    op.create_table('users',
                    sa.Column('uuid', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.Column('first_name', sa.String(length=50), nullable=True),
                    sa.Column('last_name', sa.String(length=50), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('role', sa.String(length=255), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('uuid'),
                    schema='users'
                    )
    op.create_table('refresh_tokens',
                    sa.Column('uuid', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('active_till', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.users.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('uuid'),
                    schema='users'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens', schema='users')
    op.drop_table('users', schema='users')
    op.drop_table('roles', schema='users')
    # ### end Alembic commands ###
