"""oauth-table

Revision ID: c1080ff0a3fc
Revises: 7f5b408e322e
Create Date: 2024-03-13 17:00:00.061533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1080ff0a3fc'
down_revision: Union[str, None] = '7f5b408e322e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('oauth',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('oauth_source', sa.String(length=50), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_in', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid'),
    schema='users'
    )

    op.execute("""
     INSERT INTO users.oauth (uuid, email, first_name, last_name, access_token,
     refresh_token, token_type, expires_in, created_at, user_id, oauth_source)
     SELECT uuid, default_email, first_name, last_name, access_token,
     refresh_token, token_type, expires_in, created_at, user_id, 'yandex'
     FROM users.yandex_oauth
     """)

    op.drop_table('yandex_oauth', schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    op.create_table('yandex_oauth',
                    sa.Column('uuid', sa.UUID(), nullable=False),
                    sa.Column('default_email', sa.String(length=255), nullable=False),
                    sa.Column('first_name', sa.String(length=255), nullable=True),
                    sa.Column('last_name', sa.String(length=255), nullable=True),
                    sa.Column('access_token', sa.Text(), nullable=False),
                    sa.Column('refresh_token', sa.Text(), nullable=False),
                    sa.Column('token_type', sa.String(length=50), nullable=False),
                    sa.Column('expires_in', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.users.uuid'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('default_email'),
                    sa.UniqueConstraint('uuid'),
                    schema='users'
                    )

    op.execute("""
     INSERT INTO users.yandex_oauth (uuid, email, first_name, last_name, access_token,
     refresh_token, token_type, expires_in, created_at, user_id, oauth_source)
     SELECT uuid, default_email, first_name, last_name, access_token,
     refresh_token, token_type, expires_in, created_at, user_id
     FROM users.oauth WHERE oauth_source = 'yandex'
     """)
    op.drop_table('oauth', schema='users')
    # ### end Alembic commands ###
