default_roles = [
    {'role': 'admin', 'resource': 'films', 'verb': 'read'},
    {'role': 'admin', 'resource': 'films', 'verb': 'write'},
    {'role': 'admin', 'resource': 'films', 'verb': 'delete'},
    {'role': 'admin', 'resource': 'persons', 'verb': 'read'},
    {'role': 'admin', 'resource': 'persons', 'verb': 'write'},
    {'role': 'admin', 'resource': 'persons', 'verb': 'delete'},
    {'role': 'admin', 'resource': 'genres', 'verb': 'read'},
    {'role': 'admin', 'resource': 'genres', 'verb': 'write'},
    {'role': 'admin', 'resource': 'genres', 'verb': 'delete'},
    {'role': 'admin', 'resource': 'users', 'verb': 'read'},
    {'role': 'admin', 'resource': 'users', 'verb': 'write'},
    {'role': 'admin', 'resource': 'users', 'verb': 'delete'},
    {'role': 'admin', 'resource': 'roles', 'verb': 'read'},
    {'role': 'admin', 'resource': 'roles', 'verb': 'write'},
    {'role': 'admin', 'resource': 'roles', 'verb': 'delete'},
    {'role': 'user', 'resource': 'films', 'verb': 'read'},
    {'role': 'user', 'resource': 'persons', 'verb': 'read'},
    {'role': 'user', 'resource': 'genres', 'verb': 'read'},
    {'role': 'user', 'resource': 'users', 'verb': 'read'},
    {'role': 'user', 'resource': 'users', 'verb': 'write'},
    {'role': 'user', 'resource': 'users', 'verb': 'delete'}
]
