"""add-column-for-scenario

Revision ID: 2095c99640ff
Revises: 3908b095574e
Create Date: 2024-05-04 22:47:26.785296

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2095c99640ff'
down_revision: Union[str, None] = '3908b095574e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    notificationscenario = postgresql.ENUM(
        'DAILY', 'WEEKLY', 'MONTHLY', 'WELCOME', 'BIRTHDAY', 'MAILINGS', 'NEWS',
        name='taskscenario'
    )
    notificationscenario.create(op.get_bind())

    op.add_column('tasks', sa.Column(
        'scenario',
        sa.Enum(
            'DAILY',
            'WEEKLY',
            'MONTHLY',
            'WELCOME',
            'BIRTHDAY',
            'MAILINGS',
            'NEWS',
            name='taskscenario'
        ),
        nullable=False,
        server_default='DAILY'
    ), schema='notifications')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'scenario', schema='notifications')

    notificationscenario = postgresql.ENUM(
        'DAILY', 'WEEKLY', 'MONTHLY', 'WELCOME', 'BIRTHDAY', 'MAILINGS', 'NEWS',
        name='taskscenario'
    )
    notificationscenario.drop(op.get_bind())
    # ### end Alembic commands ###
