"""add-table-websocket

Revision ID: 3516c3b6d8d4
Revises: 2095c99640ff
Create Date: 2024-05-04 23:08:46.259542

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3516c3b6d8d4'
down_revision: Union[str, None] = '2095c99640ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websocket_connections',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('websocket_id', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='notifications'
                    )
    op.create_index(
        'ix_websocket_connections_user_id',
        'websocket_connections',
        ['user_id'],
        unique=False, schema='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_websocket_connections_user_id',
        table_name='websocket_connections',
        schema='notifications'
    )
    op.drop_table('websocket_connections', schema='notifications')
    # ### end Alembic commands ###
