#!/usr/bin/env python3
import sys
import time

def main():
    email_content = sys.stdin.read()
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    with open(f"/app/mailings/fake_mail_{timestamp}.txt", 'w') as file:
        file.write(email_content)

if __name__ == "__main__":
    main()