@startuml


title
<b>Movies notifications pipeline</b>
end title

package Users {
    actor Admin
    usecase NotificationBot
    usecase WelcomeBot
}

package Starage {
    database NotificationsTasks
    database NotificationsResults
}

package Api {
    component NotificationsAPI
}

package Queues {
    queue TasksQueue
    queue NotificationsQueue
    queue EnrichedQueue
    queue DLQ
    queue ToSending
}

package Workers {
    component CreationWorker
    component EnrichingWorker
    component PreSenderWorker
    component DeadletterWorker
    component SenderWorker
}

package Mailing {
    component EMial
    component SMS
    component Push
}

Admin -down-> NotificationsAPI
NotificationBot  -down-> NotificationsAPI
WelcomeBot  -down-> NotificationsAPI
NotificationsAPI -right-> TasksQueue
TasksQueue --down-> CreationWorker
CreationWorker --up-> NotificationsQueue
CreationWorker --up-> DLQ
NotificationsQueue --down-> EnrichingWorker
EnrichingWorker --up-> EnrichedQueue
EnrichedQueue --down-> PreSenderWorker
PreSenderWorker --up-> ToSending
ToSending --down-> SenderWorker
SenderWorker --down-> NotificationsResults
CreationWorker --down-> NotificationsTasks
SenderWorker --down-> Mailing
@enduml