@startuml


title
<b>Movies notifications pipeline</b>
end title

package Users {
    actor Admin
    usecase NotificationBot
    usecase WelcomeBot
}

package Starage {
    database NotificationsTasks
    database NotificationsResults
}

package Api {
    component NotificationsAPI
}

package Queues {
    queue TasksQueue
    queue NotificationsQueue
    queue EnrichedQueue
    queue DLQ
    queue ToSending
}

package Workers {
    component CreationWorker
    component EnrichingWorker
    component SenderWorker
    component DeadletterWorker
    component SenderWorker
}

package Mailing {
    component EMial
    component SMS
    component Push
}




@enduml