@startuml
skinparam componentStyle uml2
actor StatClient
component APIStat
component APIService
queue Kafka
database Clickhouse
control ETLEvents
control ETLViews

StatClient -> APIStat
APIStat -> APIService
APIService -> Kafka
Kafka -> ETLEvents
ETLEvents -down-> Clickhouse
Kafka -down-> ETLViews
ETLViews -down-> Clickhouse
@enduml
