@startuml
'https://plantuml.com/sequence-diagram

title UGC Sequence

actor AuthorizedUser
actor UnauthorizedUser
participant UGCApi
database UGCDatabase




== LIKE AUTHORIZED ==
autonumber
AuthorizedUser -> UGCApi: POST /api/v1/like uuid = bool
UGCApi -> UGCDatabase: save like
UGCDatabase -> UGCApi: OK
UGCApi -> AuthorizedUser: OK
autonumber stop

autonumber 1
AuthorizedUser -> UGCApi: GET /api/v1/is_liked uuid
UGCApi -> UGCDatabase: check like
UGCDatabase -> UGCApi: OK
UGCApi -> AuthorizedUser: OK
autonumber stop

== LIKE UNAUTHORIZED ==

autonumber 1
UnauthorizedUser -> UGCApi: POST /api/v1/like = bool
UGCApi -> UnauthorizedUser: Error
autonumber stop
== COMMENT AUTHORIZED ==
autonumber 1
AuthorizedUser -> UGCApi: POST /api/v1/comment uuid
UGCApi -> UGCDatabase: save comment
UGCDatabase -> UGCApi: OK
UGCApi -> AuthorizedUser: OK
autonumber stop

autonumber 1
AuthorizedUser -> UGCApi: GET /api/v1/all_comments uuid
UGCApi -> UGCDatabase: get comments
UGCDatabase -> UGCApi: OK
UGCApi -> AuthorizedUser: OK
autonumber stop

== COMMENT UNAUTHORIZED ==
autonumber 1
UnauthorizedUser -> UGCApi: POST /api/v1/comment uuid
UGCApi -> UnauthorizedUser: Error
autonumber stop
autonumber 1
UnauthorizedUser -> UGCApi: GET /api/v1/all_comments uuid
UGCApi -> UnauthorizedUser: Error
autonumber stop

== FAVORITE AUTHORIZED ==

autonumber 1
AuthorizedUser -> UGCApi: POST /api/v1/save_to_favorite uuid
UGCApi -> UGCDatabase: save favorite
UGCDatabase -> UGCApi: OK
UGCApi -> AuthorizedUser: OK
autonumber stop
autonumber 1
AuthorizedUser -> UGCApi: POST /api/v1/remove_from_favorites uuid
UGCApi -> UGCDatabase: remove favorite
UGCDatabase -> UGCApi: OK
UGCApi -> AuthorizedUser: OK
autonumber stop
autonumber 1
AuthorizedUser -> UGCApi: GET /api/v1/is_saved_to_favorites
UGCApi -> UGCDatabase: check favorite
UGCDatabase -> UGCApi: OK
UGCApi -> AuthorizedUser: OK
autonumber stop


== FAVORITE UNAUTHORIZED ==
autonumber 1
UnauthorizedUser -> UGCApi: POST /api/v1/save_to_favorite uuid
UGCApi -> UnauthorizedUser: Error

autonumber stop
autonumber 1
UnauthorizedUser -> UGCApi: POST /api/v1/remove_from_favorites uuid
UGCApi -> UnauthorizedUser: Error
autonumber stop

autonumber 1
UnauthorizedUser -> UGCApi: GET /api/v1/is_saved_to_favorites
UGCApi -> UnauthorizedUser: Error
autonumber stop
@enduml