@startuml
skinparam componentStyle uml2
actor AuthorizedUser
actor UnauthorizedUser
component UGCApi
database UGCDatabase


AuthorizedUser -> UGCApi
UGCApi -> UGCDatabase
UnauthorizedUser -up-> UGCApi
@enduml