@startuml
'https://plantuml.com/sequence-diagram

actor AuthorizedUser
actor UnauthorizedUser
participant UGCApi
database UGCDatabase
participant AuthServer
database UsersDatabase


autonumber

== LIKE ==

AuthorizedUser -> UGCApi: POST /api/v1/like
AuthorizedUser -> UGCApi: POST /api/v1/unlike
AuthorizedUser -> UGCApi: GET /api/v1/is_liked

== COMMENT ==
AuthorizedUser -> UGCApi: POST /api/v1/comment

== FAVORITE ==
AuthorizedUser -> UGCApi: POST /api/v1/save_to_favorites
AuthorizedUser -> UGCApi: POST /api/v1/remove_from_favorites
AuthorizedUser -> UGCApi: GET /api/v1/is_saved_to_favorites

@enduml