@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam componentStyle uml2


actor AuthorizedUser
actor UnauthorizedUser
component UGCApi
database UGCDatabase


AuthorizedUser -> UGCApi
UGCApi -> UGCDatabase
UnauthorizedUser -up-> UGCApi
@enduml