name: Flake8 with Reviewdog
on: [pull_request]
jobs:
  flake8_reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cleanup Github-Actions bot comments
        continue-on-error: true
        run: |
            sh ./.ci/github_comments_cleanup.sh "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}" "github-actions[bot]" "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8 with Reviewdog
        uses: reviewdog/action-flake8@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Публикация комментариев в pull request
          filter_mode: diff_context # Проверка всех всех всех файлов
          fail_on_error: true # true, чтобы процесс проверки завершился с ошибкой, если найдены предупреждения